spring:
  application:
    name: contract-service

  datasource:
    url: jdbc:postgresql://localhost:5432/contractdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
